// Generated by scripts/generate-create-package-versions.mjs. Do not edit by hand.
// Run: node scripts/generate-create-package-versions.mjs
export const createPackageVersions = {
  '@vanrot/behavior': '0.1.2',
  '@vanrot/cli': '0.2.3',
  '@vanrot/config': '0.1.2',
  '@vanrot/forge': '0.2.2',
  '@vanrot/formatters': '0.1.1',
  '@vanrot/router': '0.2.1',
  '@vanrot/runtime': '0.1.1',
  '@vanrot/seo': '0.1.1',
  '@vanrot/ui': '0.1.1',
  '@vanrot/vite-plugin': '0.2.2',
} as const;

export type CreatePackageName = keyof typeof createPackageVersions;

export function createRegistryDependencyVersion(name: CreatePackageName): string {
  return `^${createPackageVersions[name]}`;
}
