import type { DocsSectionLink } from '../../../shared/docs-content.ts';

export const configurationMaintenanceArticle = {
  "key": "configurationMaintenance",
  "section": "framework",
  "path": "/docs/configuration/maintenance",
  "label": "Maintenance",
  "title": "Configuration Maintenance",
  "summary": "Configuration maintenance covers migration, recovery, validation, diagnostics, and generated-domain editing in @vanrot/config.",
  "status": "production-ready-through-phase-13",
  "sections": [
    {
      "id": "migrate-recover",
      "title": "Migrate and recover",
      "body": "Migrate and recover are explicit because config changes can affect every package. Migrate renders the canonical current config shape, while recover restores a usable config when the local file is missing or malformed.",
      "points": [
        "Use migrate when package versions introduce a new config shape.",
        "Use recover when the config file cannot be loaded.",
        "Run validation after either operation before changing app code."
      ],
      "code": {
        "title": "Maintenance APIs",
        "code": "import { migrateVanrotConfig, recoverVanrotConfig, validateVanrotConfig } from '@vanrot/config';\\n\\nawait migrateVanrotConfig({ cwd: process.cwd() });\\nawait recoverVanrotConfig({ cwd: process.cwd() });\\nvalidateVanrotConfig({});"
      }
    },
    {
      "id": "diagnostics",
      "title": "Diagnostics",
      "body": "Config diagnostics should explain what setting is invalid and what the developer should change next. Formatting belongs in the config package so CLI, Vite, and tests report the same message shape.",
      "points": [
        "Use formatConfigDiagnostic for user-facing output.",
        "Keep diagnostic severity meaningful instead of treating every issue as fatal.",
        "Prefer one precise diagnostic over several cascading errors from the same bad value."
      ]
    },
    {
      "id": "generated-domains",
      "title": "Generated domains",
      "body": "Generated-domain helpers let tools update their own config block without taking ownership of the whole file. This matters because user-authored config should remain readable and reviewable after automated repairs.",
      "points": [
        "Mark generated domains clearly.",
        "Only remove a domain when it was generated by Vanrot tooling.",
        "Keep hand-written project decisions outside generated sections."
      ]
    }
  ]
} as const;

const sectionLinks = configurationMaintenanceArticle.sections.map((section) => ({
  id: section.id,
  title: section.title,
})) satisfies readonly DocsSectionLink[];

export class MaintenancePage {
  title(): string {
    return configurationMaintenanceArticle.title;
  }

  summary(): string {
    return configurationMaintenanceArticle.summary;
  }

  sectionLinks(): readonly DocsSectionLink[] {
    return sectionLinks;
  }

  section0Body = configurationMaintenanceArticle.sections[0].body;
  section1Body = configurationMaintenanceArticle.sections[1].body;
  section2Body = configurationMaintenanceArticle.sections[2].body;
  section0Points = configurationMaintenanceArticle.sections[0].points ?? [];
  section1Points = configurationMaintenanceArticle.sections[1].points ?? [];
  section2Points = configurationMaintenanceArticle.sections[2].points ?? [];
  section0Code = configurationMaintenanceArticle.sections[0].code?.code ?? '';
}
