import type { DocsSectionLink } from '../../shared/docs-content.ts';

export const generatedFilesArticle = {
  "key": "generatedFiles",
  "section": "reference",
  "path": "/docs/generated-files",
  "label": "Generated Files",
  "title": "Generated Files And Directories",
  "summary": "Understand generated files Vanrot users should expect in starter apps, config flows, route workflows, and project intelligence output.",
  "status": "phase-24-active",
  "sections": [
    {
      "id": "starter-files",
      "title": "Starter Files",
      "body": "Starter projects use familiar JavaScript files such as package.json, tsconfig.json, vite.config.ts, and vanrot.config.ts. The docs explain which package owns each file."
    },
    {
      "id": "route-files",
      "title": "Route Files",
      "body": "src/routes.ts is the framework-owned convention for route refs, route paths, and route metadata. Docs and examples point users to named route refs instead of repeated strings."
    },
    {
      "id": "project-intelligence",
      "title": "Project Intelligence",
      "body": ".vanrot/project-map.json is generated by vr map and belongs to the devtools and project intelligence story. It is documented as local metadata, not as a Phase 25 AI bundle."
    }
  ]
} as const;

const sectionLinks = generatedFilesArticle.sections.map((section) => ({
  id: section.id,
  title: section.title,
})) satisfies readonly DocsSectionLink[];

export class GeneratedFilesPage {
  title(): string {
    return generatedFilesArticle.title;
  }

  summary(): string {
    return generatedFilesArticle.summary;
  }

  sectionLinks(): readonly DocsSectionLink[] {
    return sectionLinks;
  }

  section0Body = generatedFilesArticle.sections[0].body;
  section1Body = generatedFilesArticle.sections[1].body;
  section2Body = generatedFilesArticle.sections[2].body;
}
