import { vanrotAiRuleSection, type NormalizedVanrotAiConfig } from '@vanrot/config';
import { commandInvocation, commandName } from '../commands/metadata.js';

export interface CreateAiRulesOptions {
  ai: NormalizedVanrotAiConfig;
}

export function createAiRules(options: CreateAiRulesOptions): string {
  const sections = new Map<string, string>([
    [vanrotAiRuleSection.projectRules, projectRulesSection()],
    [vanrotAiRuleSection.commands, commandsSection()],
    [vanrotAiRuleSection.fileConventions, fileConventionsSection()],
    ...options.ai.rules.customSections.map((section) => [
      section.id,
      `## ${section.title}\n\n${section.body}\n`,
    ] as const),
  ]);

  const body = options.ai.rules.enabledSections
    .map((sectionId) => sections.get(sectionId))
    .filter((section): section is string => section !== undefined)
    .join('\n');

  return [
    '# Vanrot AI Rules',
    '',
    '<!-- Generated by Vanrot. Edit vanrot.config.ts to customize sections. -->',
    '',
    'Vanrot is a compiler-first UI framework built around clean file separation, tiny runtime output, strict conventions, and provider-neutral project intelligence.',
    '',
    body.trim(),
    '',
  ].join('\n');
}

function projectRulesSection(): string {
  return [
    '## Project Rules',
    '',
    '- Use guard clauses instead of nested control flow.',
    '- Use signals for state.',
    '- Never put UI markup in TypeScript.',
    '- Never put application logic in HTML.',
    '- Prefer i18n-ready text for user-facing strings.',
    '- Prefer accessible UI primitives and keyboard-friendly behavior.',
    '- Read `.vanrot/project-map.json` before making broad project changes.',
    '- Do not assume an AI provider is required for Vanrot projects.',
    '',
  ].join('\n');
}

function commandsSection(): string {
  return [
    '## Commands',
    '',
    `- Start development with \`${commandInvocation(commandName.dev)}\`.`,
    `- Generate project intelligence with \`${commandInvocation(commandName.map)}\`.`,
    `- Check project health with \`${commandInvocation(commandName.doctor)}\`.`,
    '',
  ].join('\n');
}

function fileConventionsSection(): string {
  return [
    '## File Conventions',
    '',
    '- Use role-based file suffixes such as `.component.ts`, `.page.ts`, `.dialog.ts`, `.layout.ts`, `.widget.ts`, and `.form.ts`.',
    '- Keep component TypeScript, HTML, and CSS in sibling role files.',
    '- Use scoped CSS for component styling.',
    '',
  ].join('\n');
}
