export {
  projectMapGraphSchemaVersion,
  runtimeGraphSchemaVersion,
  type AiRulesGraphMetadata,
  type CompilerGraphMetadata,
  type GraphManifestStatus,
  type GraphStaleState,
  type NormalizedGraphManifest,
  type ProjectGraph,
  type ProjectGraphEdge,
  type ProjectGraphEdgeKind,
  type ProjectGraphManifest,
  type ProjectGraphNode,
  type ProjectGraphNodeKind,
  type ProjectMapI18n,
  type ProjectMapRoles,
  type ProjectRoleFile,
  type RouteGraphEntry,
  type RuntimeGraphEdge,
  type RuntimeGraphEdgeKind,
  type RuntimeGraphEvent,
  type RuntimeGraphNode,
  type RuntimeGraphNodeKind,
} from './graph/types.js';
export { normalizeGraphManifest } from './graph/normalize.js';
