import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const readProjectFile = path => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');

describe('homepage finale visual contract', () => {
  const spiral = readProjectFile('apps/vanrot-site/src/pages/home/home-spiral.widget.ts');
  const interactions = readProjectFile('apps/vanrot-site/src/pages/home/home-interactions.widget.ts');
  const template = readProjectFile('apps/vanrot-site/src/pages/home/home.page.html');
  const styles = readProjectFile('apps/vanrot-site/src/pages/home/home.page.css');

  it('flies the manifesto through a perspective dolly with focus falloff', () => {
    expect(spiral).toContain('const dollyPerspective = 1000;');
    expect(spiral).toContain('const dollyLineGap = 620;');
    expect(spiral).toContain('const dollyFanInSpan = 0.3;');
    expect(spiral).toContain('const dollyPassStart = 0.55;');
    expect(spiral).toContain('const dollyPassSpan = 0.32;');
    expect(spiral).toContain('const dollyFogDepth = 2.4;');
    expect(spiral).toContain('const cameraEase = (t: number): number => t * t * (0.35 + 0.65 * t);');
    expect(spiral).toContain("section.style.setProperty('--dolly-perspective', `${dollyPerspective}px`);");
    expect(spiral).toContain('const cameraZ = cameraEase(clamp01(zoomProgress)) * dollyTravel;');
    expect(spiral).toContain('const fanOut = smooth(clamp01(zoomProgress / dollyFanInSpan));');
    expect(spiral).toContain('const z = cameraZ - i * dollyLineGap * fanOut;');
    expect(spiral).toContain('const passT = smooth(clamp01((z - dollyPerspective * dollyPassStart) / (dollyPerspective * dollyPassSpan)));');
    expect(spiral).toContain('const fogT = smooth(clamp01(-z / (dollyLineGap * dollyFogDepth)));');
    expect(spiral).toContain('const opacity = (1 - passT) * (1 - dollyFogDim * fogT);');
    expect(spiral).toContain('line.style.transform = `translateZ(${z.toFixed(1)}px)`;');
    expect(spiral).toContain('line.style.filter = blur > 0.05 ? `blur(${blur.toFixed(2)}px)` : \'\';');
    expect(spiral).toContain('line.style.textShadow =');
    expect(spiral).toContain('const canvasDprCap = 1;');
    expect(spiral).toContain('const starDensity = 0.055;');
    expect(spiral).toContain('const progressFollow = 0.2;');
    expect(spiral).toContain('progress += (targetProgress - progress) * progressFollow;');
    expect(spiral).toContain('ctx.beginPath();');
    expect(spiral).toContain('ctx.stroke();');
    expect(spiral).not.toContain('drawZoomedLines');
    expect(spiral).not.toContain('drawFragments');
    expect(spiral).not.toContain('captureLines');
    expect(spiral).not.toContain('CapturedLine');
    expect(spiral).not.toContain('lineShatterPoint');
    expect(spiral).not.toContain('fragmentGlyphs');
    expect(spiral).not.toContain('dissolveParticleCount');
    expect(styles).toContain('perspective: var(--dolly-perspective, 1000px);');
    expect(styles).toContain('transform-style: preserve-3d;');
    expect(styles).toContain('will-change: transform, opacity, filter;');
  });

  it('folds the package wall into the pinned finale as the post-zoom stage', () => {
    expect(template).not.toContain('data-vr-finale-stage');
    expect(template).not.toContain('data-vr-rail-track');
    expect(template).not.toContain('data-vr-finale-carousel');
    expect(template).not.toContain('data-vr-rail-counter');
    expect(template).not.toContain('home-package-wall');
    expect(template).toContain('<div class="finale-wall" data-vr-package-wall>');
    expect(spiral).toContain('type PhaseMap = { manifestoEnd: number; zoomEnd: number; wallSettleEnd: number };');
    expect(spiral).toContain('const desktopPhase: PhaseMap = { manifestoEnd: 0.3, zoomEnd: 0.52, wallSettleEnd: 0.82 };');
    expect(spiral).toContain('const mobilePhase: PhaseMap = { manifestoEnd: 0.48, zoomEnd: 0.76, wallSettleEnd: 0.88 };');
    expect(spiral).toContain('const wallFadeSpan = 0.08;');
    expect(spiral).toContain("section.style.setProperty('--wp', clamp01((progress - phase.zoomEnd) / wallFadeSpan).toFixed(4));");
    expect(spiral).toContain('const wallProgress = (): number =>');
    expect(spiral).toContain('clamp01((progress - phase.zoomEnd) / (phase.wallSettleEnd - phase.zoomEnd));');
    expect(spiral).not.toContain('carousel');
    expect(spiral).not.toContain('Carousel');
    expect(spiral).not.toContain('railTrack');
    expect(spiral).not.toContain('finale-stage');
    expect(styles).toContain('/* ── Finale: manifesto → depth dolly → package wall handoff ────────── */');
    expect(styles).toContain('height: 260svh;');
    expect(styles).toContain('.finale-wall {');
    expect(styles).toContain('opacity: var(--wp, 0);');
    expect(styles).not.toContain('.finale-stage');
    expect(styles).not.toContain('.finale-carousel');
    expect(styles).not.toContain('.rail-track');
    expect(styles).not.toContain('.home-package-wall');
  });

  it('adds a 6 by 3 opposing fisheye comparison wall with all packages moving', () => {
    expect(interactions).toContain('setupPackageWallScene()');
    expect(template).toContain('data-vr-package-wall');
    expect(template).toContain('data-vr-package-wall-grid');
    expect(template).toContain('data-vr-package-wall-source');
    expect(spiral).toContain('export function setupPackageWallScene(): Dispose');
    expect(spiral).toContain('type PackageWallCard = { element: HTMLElement; row: number; column: number };');
    expect(spiral).toContain('const packageWallColumns = 6;');
    expect(spiral).toContain('const packageWallVisibleColumns = 5;');
    expect(spiral).toContain('const packageWallRows = 3;');
    expect(spiral).toContain('const packageWallSlots = packageWallColumns * packageWallRows;');
    expect(spiral).toContain('const packageWallLaneSpeed = 0.000016;');
    expect(spiral).toContain('const packageWallScrollLaneSpeed = 0.0018;');
    expect(spiral).toContain('window.scrollY * packageWallScrollLaneSpeed');
    expect(spiral).toContain('type WallLens = {');
    expect(spiral).toContain('const packageWallFlatColumns = 5.2;');
    expect(spiral).toContain('const packageWallLensDistortion = -0.07;');
    expect(spiral).toContain('function wallQuadTransform(width: number, height: number, quad: WallPoint[]): string {');
    expect(spiral).toContain('function applyWallTile(element: HTMLElement, row: number, slot: number, lens: WallLens): void {');
    expect(spiral).toContain('const rowDirection = card.row === 1 ? -1 : 1;');
    expect(spiral).toContain('const normalizedSlot = positiveModulo(card.column + rowDirection * laneProgress, packageWallColumns);');
    expect(spiral).toContain('const visualSlot = normalizedSlot > packageWallVisibleColumns ? normalizedSlot - packageWallColumns : normalizedSlot;');
    expect(spiral).toContain('applyWallTile(card.element, card.row, visualSlot, lens);');
    expect(spiral).toContain('window.requestAnimationFrame(renderWall);');
    expect(spiral).toContain('visibilityObserver.observe(section);');
    expect(spiral).not.toContain('const packageWallSwapMs =');
    expect(spiral).not.toContain('overflowIndex = packageWallSlots +');
    expect(spiral).not.toContain('window.setInterval(swapOverflowCard');
    expect(styles).toContain('/* ── Package wall: concave fisheye manifest (inside-sphere lens) ───── */');
    expect(styles).toContain('top: clamp(54px, 6.5vh, 86px);');
    expect(styles).toContain('.package-wall-frame {\n  position: relative;\n  width: 100%;\n  height: 100%;');
    expect(styles).toContain('display: block;');
    expect(styles).toContain('border-radius: 2px;');
    expect(styles).toContain('transform-origin: 0 0;');
    expect(styles).toContain('radial-gradient(115% 115% at 50% 50%');
    expect(styles).not.toContain('margin-top: -100vh;');
    expect(styles).not.toContain('margin-top: -100svh;');
    expect(styles).not.toContain('margin: 0 calc(50vw - 50%);');
    expect(styles).not.toContain('width: 100vw;');
    expect(styles).not.toContain('margin: 36px 50% 0;');
    expect(styles).not.toContain('width: min(2160px, 112vw);');
    expect(styles).not.toContain('width: clamp(150px, 14.5%, 220px);');
    expect(styles).not.toContain('grid-template-columns: repeat(5, minmax(0, 1fr));');
    expect(styles).not.toContain('.package-wall-card--swap');
  });
});
