import type { DocsSectionLink } from '../../../shared/docs-content.ts';

export const vitePluginVirtualModulesArticle = {
  "key": "vitePluginVirtualModules",
  "section": "framework",
  "path": "/docs/vite-plugin/virtual-modules",
  "label": "Virtual Modules",
  "title": "Vite Plugin Virtual Modules",
  "summary": "Virtual modules let generated Vanrot JavaScript import scoped CSS and original source through Vite without writing temporary generated files.",
  "status": "production-ready-through-phase-12",
  "sections": [
    {
      "id": "module-purpose",
      "title": "Module purpose",
      "body": "The plugin uses public virtual module ids for generated imports and resolved internal ids for Vite loading. Source virtual modules expose the original role file content to downstream transforms, while CSS virtual modules expose the scoped CSS generated by the compiler for the owning component.",
      "points": [
        "virtual:vanrot-source: points at original role source.",
        "virtual:vanrot-css: points at generated scoped CSS.",
        "Resolved \\0vanrot: ids stay internal to Vite's plugin pipeline."
      ],
      "code": {
        "title": "Generated CSS import",
        "code": "import 'virtual:vanrot-css:%2Frepo%2Fsrc%2Fcounter.component.ts';\n\nconst component = { createComponent };\nexport default component;"
      }
    },
    {
      "id": "resolve-and-load",
      "title": "Resolve and load",
      "body": "resolveId translates public Vanrot virtual ids into internal resolved ids. load decodes those resolved ids and returns either generated CSS from the compile cache or the original source file contents. The split keeps generated artifacts in memory and lets Vite continue to own module caching.",
      "points": [
        "CSS virtual modules return generated CSS plus the matching CSS source map when available.",
        "Source virtual modules read the original source file and then pass through OXC transforms.",
        "Unknown ids return undefined so other Vite plugins can continue resolving normally."
      ],
      "code": {
        "title": "Source virtual import",
        "code": "const sourceModule = await import(\n  'virtual:vanrot-source:%2Frepo%2Fsrc%2Fcounter.component.ts'\n);"
      }
    },
    {
      "id": "asset-queries",
      "title": "Asset queries",
      "body": "The plugin keeps static asset queries attached to the original source path when a virtual source import points back at an asset reference. This prevents generated source indirection from breaking Vite's URL, raw, worker, or other static asset query handling.",
      "points": [
        "Asset query imports resolve relative to the decoded owner file path.",
        "Virtual module decoding happens before static asset query fallback.",
        "The result is a normal resolved source path for Vite's asset pipeline."
      ]
    }
  ]
} as const;

const sectionLinks = vitePluginVirtualModulesArticle.sections.map((section) => ({
  id: section.id,
  title: section.title,
})) satisfies readonly DocsSectionLink[];

export class VirtualModulesPage {
  title(): string {
    return vitePluginVirtualModulesArticle.title;
  }

  summary(): string {
    return vitePluginVirtualModulesArticle.summary;
  }

  sectionLinks(): readonly DocsSectionLink[] {
    return sectionLinks;
  }

  section0Body = vitePluginVirtualModulesArticle.sections[0].body;
  section1Body = vitePluginVirtualModulesArticle.sections[1].body;
  section2Body = vitePluginVirtualModulesArticle.sections[2].body;
  section0Points = vitePluginVirtualModulesArticle.sections[0].points ?? [];
  section1Points = vitePluginVirtualModulesArticle.sections[1].points ?? [];
  section2Points = vitePluginVirtualModulesArticle.sections[2].points ?? [];
  section0Code = vitePluginVirtualModulesArticle.sections[0].code?.code ?? '';
  section1Code = vitePluginVirtualModulesArticle.sections[1].code?.code ?? '';
}
