export const routeDiagnosticCodes = {
  duplicatePath: 'VR_ROUTE_DUPLICATE_PATH',
  invalidParentPath: 'VR_ROUTE_INVALID_PARENT_PATH',
  missingRenderTarget: 'VR_ROUTE_MISSING_RENDER_TARGET',
  invalidParamName: 'VR_ROUTE_INVALID_PARAM_NAME',
  missingParam: 'VR_ROUTE_MISSING_PARAM',
  unknownParam: 'VR_ROUTE_UNKNOWN_PARAM',
  unknownQuery: 'VR_ROUTE_UNKNOWN_QUERY',
  queryMetadataRequired: 'VR_ROUTE_QUERY_METADATA_REQUIRED',
  breadcrumbParentMissing: 'VR_ROUTE_BREADCRUMB_PARENT_MISSING',
  breadcrumbParamImpossible: 'VR_ROUTE_BREADCRUMB_PARAM_IMPOSSIBLE',
  invalidTemplateRef: 'VR_ROUTE_INVALID_TEMPLATE_REF',
  childBeforeParent: 'VR_CHILD_BEFORE_PARENT',
  duplicateIndexRoute: 'VR_DUPLICATE_INDEX_ROUTE',
  invalidIndexLayout: 'VR_INVALID_INDEX_LAYOUT',
  layoutMissingComponent: 'VR_LAYOUT_MISSING_COMPONENT',
  layoutWithoutChildren: 'VR_LAYOUT_WITHOUT_CHILDREN',
  pageHasChildren: 'VR_PAGE_HAS_CHILDREN',
  redirectHasRenderTarget: 'VR_REDIRECT_HAS_RENDER_TARGET',
  redirectHasChildren: 'VR_REDIRECT_HAS_CHILDREN',
  redirectTargetMissing: 'VR_REDIRECT_TARGET_MISSING',
  redirectLoop: 'VR_REDIRECT_LOOP',
  invalidGuard: 'VR_ROUTE_INVALID_GUARD',
  invalidGuardResult: 'VR_ROUTE_INVALID_GUARD_RESULT',
  guardRedirectTargetMissing: 'VR_GUARD_REDIRECT_TARGET_MISSING',
  guardRedirectLoop: 'VR_GUARD_REDIRECT_LOOP',
  redirectHasPreloadPolicy: 'VR_REDIRECT_HAS_PRELOAD_POLICY',
  redirectHasKeepAlivePolicy: 'VR_REDIRECT_HAS_KEEP_ALIVE_POLICY',
  preloadWithoutLazyTarget: 'VR_PRELOAD_WITHOUT_LAZY_TARGET',
  routePreloadFailed: 'VR_ROUTE_PRELOAD_FAILED',
  keepAliveIdentityMissing: 'VR_KEEP_ALIVE_IDENTITY_MISSING',
  keepAliveRestoreBlocked: 'VR_KEEP_ALIVE_RESTORE_BLOCKED',
} as const;

export type RouteDiagnosticCode =
  (typeof routeDiagnosticCodes)[keyof typeof routeDiagnosticCodes];
