import type { DocsSectionLink } from '../../../shared/docs-content.ts';

export const cliConfigMaintenanceArticle = {
  "key": "cliConfigMaintenance",
  "section": "framework",
  "path": "/docs/cli/config-maintenance",
  "label": "Config Maintenance",
  "title": "CLI Config Maintenance",
  "summary": "Configuration commands keep vanrot.config.ts present, canonical, repairable, and aligned with package expectations.",
  "status": "production-ready-through-phase-13",
  "sections": [
    {
      "id": "config-commands",
      "title": "Config commands",
      "body": "The config command family handles canonical config creation and repair. Use it when the config file is missing, old, generated by an earlier package version, or inconsistent with the source layout used by Vite and the compiler.",
      "points": [
        "Use migrate when the config needs to be rewritten into the current canonical shape.",
        "Use recover when the config file was damaged or removed.",
        "Use update config when the generated config surface needs to be refreshed."
      ],
      "code": {
        "title": "Repair config",
        "code": "vr config migrate\\nvr config recover\\nvr update config"
      }
    },
    {
      "id": "when-to-run",
      "title": "When to run",
      "body": "Run config maintenance before debugging compiler or Vite plugin failures caused by missing roots. The config package normalizes defaults, but repair commands make the local file readable and explicit for humans too.",
      "points": [
        "Run after pulling a branch that changes config domains.",
        "Run after moving source files from src to a custom source root.",
        "Run before filing a bug when the project has an old config file."
      ]
    },
    {
      "id": "repair-boundary",
      "title": "Repair boundary",
      "body": "The CLI should repair Vanrot-owned config shape, not rewrite unrelated application settings. Generated domain markers are important because they let the tool update its own block without pretending to own hand-written project decisions.",
      "points": [
        "Keep application-specific settings outside generated blocks.",
        "Prefer named config domains over one large unstructured object.",
        "Review diffs after config repair because config changes affect many packages."
      ]
    }
  ]
} as const;

const sectionLinks = cliConfigMaintenanceArticle.sections.map((section) => ({
  id: section.id,
  title: section.title,
})) satisfies readonly DocsSectionLink[];

export class ConfigMaintenancePage {
  title(): string {
    return cliConfigMaintenanceArticle.title;
  }

  summary(): string {
    return cliConfigMaintenanceArticle.summary;
  }

  sectionLinks(): readonly DocsSectionLink[] {
    return sectionLinks;
  }

  section0Body = cliConfigMaintenanceArticle.sections[0].body;
  section1Body = cliConfigMaintenanceArticle.sections[1].body;
  section2Body = cliConfigMaintenanceArticle.sections[2].body;
  section0Points = cliConfigMaintenanceArticle.sections[0].points ?? [];
  section1Points = cliConfigMaintenanceArticle.sections[1].points ?? [];
  section2Points = cliConfigMaintenanceArticle.sections[2].points ?? [];
  section0Code = cliConfigMaintenanceArticle.sections[0].code?.code ?? '';
}
